/**
 * Hands generated bytes to the browser as a download.
 *
 * Nothing leaves the device: the file is assembled in memory, given a
 * short-lived object URL, and saved through a synthetic link click. The URL is
 * released a little later rather than at once, because some browsers start
 * reading it only after the click handler has returned.
 */
export function saveFile(parts: readonly BlobPart[], fileName: string, type: string): void {
  const url = URL.createObjectURL(new Blob(parts as BlobPart[], { type }));
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  link.rel = "noopener";
  link.style.display = "none";
  document.body.append(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

/** A scan name made safe to use as the stem of a file name on any operating system. */
export function fileStem(name: string): string {
  const stem = [...name]
    .map((char) => (char.charCodeAt(0) < 32 || '\\/:*?"<>|'.includes(char) ? "-" : char))
    .join("")
    .replace(/-{2,}/g, "-")
    .replace(/^[\s.-]+|[\s.-]+$/g, "");
  return stem === "" ? "scan" : stem.slice(0, 120);
}
